// Nội dung lấy từ CV — Trần Tôn Nữ Thục Anh
const P={name:"Trần Tôn Nữ",name2:"Thục Anh",role:"Project Marketing Executive",niche:"Online Marketing · E-commerce · Beauty",city:"Quận 2, TP. Hồ Chí Minh",email:"thucanh.ttn@gmail.com",phone:"(+84) 797 038 080",
intro:"Hơn 3 năm làm marketing online và thương mại điện tử trong ngành beauty. Tôi lên kế hoạch ra mắt sản phẩm, vận hành gian hàng và dẫn dắt các đội đa chức năng — từ ý tưởng đến con số cuối tháng.",
bio:["Tôi bắt đầu từ livestream và bán hàng trực tiếp, nên quen với việc nhìn phản ứng của khách theo từng phút. Sau đó chuyển sang phía thương hiệu: lập kế hoạch chiến dịch, làm việc với nhà cung cấp, đội thiết kế và các sàn.","Hiện tại tôi phụ trách marketing online cho Kérastase và L'Oréal Professionnel tại L'Oréal Việt Nam — quản lý hình ảnh trên sàn, sản xuất quà tặng, sự kiện ra mắt và các kế hoạch video trên Shopee, TikTok.","Điều tôi giữ trong mọi dự án: chiến lược phải ra được số, và số phải đến từ việc hiểu người mua."],
stats:[{v:"3+",k:"năm kinh nghiệm"},{v:"150%",k:"tăng lượng video Shopee"},{v:"125%",k:"KPI doanh số cao nhất"},{v:"9K+",k:"follower TikTok đã xây"}],
brands:["L'Oréal Professionnel","Kérastase","Matrix","Estée Lauder","Clinique","Baresoul Cosme"],
skills:[{h:"Chuyên môn",i:["Kế hoạch chiến dịch online","Vận hành sàn TMĐT","Ra mắt sản phẩm & sự kiện","Quản lý KOL / KOC & affiliate","Livestream bán hàng","Điều phối sản xuất nội dung"]},{h:"Kỹ năng",i:["Quản lý dự án","Làm việc đa chức năng","Giải quyết vấn đề","Tư duy sáng tạo","Thích ứng nhanh"]},{h:"Công cụ",i:["Microsoft Excel","Google Sheets","Canva","Nền tảng CEM / CRM","Shopee & TikTok Seller Center"]}],
edu:{school:"Đại học Kinh tế – Tài chính TP.HCM (UEF)",deg:"Cử nhân Quản trị Kinh doanh · GPA 3.7/4.0",years:"2021 — 2025",notes:["Á khoa ngành Quản trị Kinh doanh","Học bổng 50% liên tục 4 năm","Top 1 Học bổng Tài năng 2023–2024 · GPA 4.0/4.0"]},
awards:["Á khoa ngành QTKD — UEF","Top 1 Học bổng Tài năng 2023–2024","Sinh viên 5 Tốt cấp Trường 2022–2023 & 2023–2024","Giấy khen đóng góp hoạt động ngoại khoá UEF 2021–2025","Top 20 Hackathon 48H 2021 — RE-Organization","Top 20 Z-Marketer 2023","Dự án Đổi mới Xuất sắc — Project Design UEF 2023"],
cv:[{y:"06/2025 — nay",r:"Project Marketing Executive — Online MKT",c:"L'Oréal Việt Nam (Kérastase & L'Oréal Professionnel)",d:["Quản lý toàn bộ quy trình sản xuất quà tặng với nhà cung cấp và listing trên sàn, giữ 100% tính toàn vẹn danh mục.","Điều phối ~40 tài sản hình ảnh mỗi tháng (SIS, PDP, CPAS, banner) với đội thiết kế, tuân thủ 100% brand guideline.","Lên kế hoạch và tối ưu 100% CEM/CRM, kế hoạch video Shopee, hiển thị trên sàn — đóng góp 3–5% GMV mỗi tháng."]},
{y:"11/2024 — 04/2025",r:"Hospitality Intern",c:"Joetsu Skiing Resort, Nhật Bản",d:["Tối ưu quy trình nhà hàng và phối hợp liên bộ phận trong cao điểm để đảm bảo trải nghiệm khách hàng."]},
{y:"05/2024 — 11/2024",r:"Cloud (Ecom) Beauty Advisor — Freelance BA",c:"Estée Lauder Companies",d:["Dẫn livestream hằng ngày giới thiệu sản phẩm Estée Lauder, đạt 100–130% KPI tháng.","Phối hợp đội Ecommerce & Marketing để đồng bộ nội dung livestream với chiến dịch theo mùa và ra mắt sản phẩm mới."]},
{y:"11/2023 — 02/2024",r:"Brand Ambassador Livestreamer — TikTok",c:"L'Oréal Việt Nam",d:["Đồng sản xuất video khuyến mãi và dẫn livestream TikTok, đạt KPI doanh số nhóm đầu (125% tháng 11, 120% tháng 12)."]},
{y:"11/2022 — 10/2023",r:"Online Marketing & Key Account Staff",c:"Baresoul Cosme",d:["Xây kênh TikTok lên 9K+ follower; quản lý hợp tác KOL/KOC và chiến dịch affiliate, đạt 120% KPI.","Phát triển pipeline 80–100 khách B2B; đàm phán hợp đồng và quản lý phân phối cho Hasaki, Watsons, Guardian.","Dẫn livestream hằng tháng trên TikTok và Shopee, luôn đạt trên 100% chỉ tiêu."]}]};
const CAMPAIGNS=[{id:"ppd",n:"01",title:"Quảng bá hình ảnh team PPD",brand:"L'Oréal Việt Nam — Professional Products Division",year:"2026",tag:"Employer branding · Video",kpi:"People Prize · Clip 100% AI",
summary:"Hai clip dài kể câu chuyện con người và cách làm việc của team PPD — một clip dựng hoàn toàn bằng AI, và dự án được ghi nhận bằng giải People Prize.",
goal:"Team PPD cần một hình ảnh gần gũi và rõ nét trong nội bộ L'Oréal Việt Nam, thay cho những bản tin thông báo quen thuộc.",
did:["Lên ý tưởng và kịch bản cho hai clip dài về con người, nhịp làm việc và tinh thần của team.","Tự học và ứng dụng công cụ AI để dựng trọn một clip 100% bằng AI — từ hình ảnh, giọng đọc đến hậu kỳ, không cần ekip quay.","Tổ chức quay, phỏng vấn và điều phối nhân sự tham gia trong lịch làm việc thực tế.","Dựng, hoàn thiện và phát hành nội dung trên kênh nội bộ và trong sự kiện công ty."],
res:[{v:"People Prize",k:"giải thưởng nhận được"},{v:"100% AI",k:"một clip dựng hoàn toàn bằng AI"},{v:"02",k:"clip dài đã sản xuất"}],
vids:[{id:"a",l:"Clip 1 — quay thực tế"},{id:"b",l:"Clip 2 — dựng 100% bằng AI"}],
shots:["Hậu trường quay","Khung hình từ clip","Khoảnh khắc nhận giải"]},
{id:"matrix",n:"02",title:"Ra mắt Matrix store trên Shopee",brand:"Matrix (L'Oréal Việt Nam)",year:"07/2026",tag:"Ra mắt · E-commerce",kpi:"Dự án chủ trì",
summary:"Đưa Matrix lên Shopee từ con số 0: gian hàng, thông tin sản phẩm và toàn bộ bộ hình cho ngày mở bán.",
goal:"Một thương hiệu chưa có dấu chân số tại Việt Nam cần xuất hiện đầy đủ và đồng nhất ngay từ ngày đầu lên sàn.",
did:["Thiết lập gian hàng và chuẩn hoá thông tin cho toàn bộ danh mục sản phẩm.","Chuẩn bị bộ hình ảnh, video và chương trình khuyến mãi cho ngày mở bán.","Phối hợp đội nội dung, thiết kế và vận hành sàn theo một mốc thời gian chung."],
res:[{v:"07/2026",k:"thời điểm mở bán"},{v:"100%",k:"đồng nhất brand guideline"},{v:"Full",k:"danh mục lên sàn"}],
shots:["Gian hàng Shopee","Bộ hình ra mắt","Video giới thiệu sản phẩm"]},
{id:"serioxyl",n:"03",title:"Serioxyl — Độ tóc tốc độ",brand:"L'Oréal Professionnel — Serioxyl",year:"04/2026",tag:"Sự kiện ra mắt",kpi:"Ý tưởng & video",
summary:"Concept sáng tạo và video cho sự kiện ra mắt Serioxyl — một buổi giới thiệu có ngôn ngữ riêng thay vì format quen thuộc.",
goal:"Đưa một dòng chăm sóc tóc chuyên sâu đến gần nhóm khách trẻ bằng cách kể chuyện khác đi ngay từ tên gọi của sự kiện.",
did:["Phát triển concept và đặt tên cho sự kiện ra mắt.","Viết kịch bản và sản xuất video trình chiếu trong sự kiện.","Bàn giao tuyến nội dung và tài sản hình ảnh cho đội vận hành."],
res:[{v:"04/2026",k:"thời điểm tổ chức"},{v:"Concept",k:"vai trò ý tưởng"},{v:"Video",k:"hạng mục sản xuất"}],
shots:["Không gian sự kiện","Khung hình video sự kiện","Ấn phẩm / backdrop"]},
{id:"gloss",n:"04",title:"Gloss Absolu — Kérastase",brand:"Kérastase",year:"02/2026",tag:"Sự kiện · Livestream",kpi:"Content & visual",
summary:"Tuyến nội dung và toàn bộ vật liệu hình ảnh cho sự kiện Gloss Absolu, gồm cả background phiên livestream.",
goal:"Sự kiện cần một mạch nội dung thống nhất giữa sân khấu offline và phiên livestream chạy song song.",
did:["Viết tuyến nội dung cho sự kiện và kịch bản phiên livestream.","Thiết kế và điều phối background cùng bộ vật liệu hình ảnh cho livestream.","Giữ hình ảnh nhất quán giữa điểm chạm offline và online."],
res:[{v:"02/2026",k:"thời điểm tổ chức"},{v:"1",k:"phiên livestream đồng hành"},{v:"100%",k:"nhất quán hình ảnh"}],
shots:["Sân khấu sự kiện","Background livestream","Bộ vật liệu hình ảnh"]},
{id:"pickleball",n:"05",title:"The Pickleball Tournament — “Drop” mượt mà",brand:"Kérastase",year:"11/2025",tag:"Kích hoạt thương hiệu",kpi:"Sự kiện thể thao",
summary:"Giải pickleball gắn thông điệp tóc mượt, kháng nhiệt tối đa — đưa Kérastase ra khỏi salon và vào đời sống thể thao.",
goal:"Tìm một bối cảnh đời thường để nói về khả năng kháng nhiệt và độ mượt của tóc, thay vì chỉ nói trong không gian salon.",
did:["Gắn thông điệp sản phẩm vào ngôn ngữ của môn thể thao đang được cộng đồng theo đuổi.","Chuẩn bị nội dung, vật liệu hình ảnh và hạng mục trải nghiệm tại sân.","Ghi hình và biên tập nội dung hậu sự kiện cho các kênh online."],
res:[{v:"11/2025",k:"thời điểm tổ chức"},{v:"Offline",k:"trải nghiệm tại sân"},{v:"Đa kênh",k:"nội dung hậu sự kiện"}],
shots:["Toàn cảnh giải đấu","Khu trải nghiệm thương hiệu","Khoảnh khắc người chơi"]}];
const VIDEOS=[{id:"v1",l:"Video dọc — TikTok",r:"9/16"},{id:"v2",l:"Ảnh sự kiện — ngang",r:"4/3"},{id:"v3",l:"Video dọc — Shopee",r:"9/16"},{id:"v4",l:"Ảnh sản phẩm",r:"4/3"},{id:"v5",l:"Video dọc — livestream",r:"9/16"},{id:"v6",l:"Ảnh hậu trường",r:"4/3"}];
Object.assign(window,{P,CAMPAIGNS,VIDEOS});
